### ISSUE TITLE
PeerJ reference formatting

### ISSUE THREAD

**Issue by cjlortie** [rstudio/rticles#201]

**Comment by yihui** [comment]
Sorry, but I'm not familiar with PeerJ requirements. I guess we have to ask @zkamvar (#127 #134).

**Comment by zkamvar** [comment]
Hi @cjlortie, you might be able to change the citation style to "natbib" to suit your needs (see https://github.com/rstudio/rticles/pull/134#issuecomment-326339084). 

For reference, this was the configuration I used for an article from late 2017: https://github.com/everhartlab/sclerotinia-366/blob/master/doc/manuscript/manuscript.Rmd

I suspect it may be the behavior of the "indentfirst" package if you are using that since pandoc first hard-codes the bibliography in the latex file and then renders the PDF.
