### ISSUE TITLE
rticles IEEE template fails when using bookdown cross-referencing for formula

### ISSUE THREAD

**Issue by rainer-rq-koelle** [rstudio/rticles#289]
Hi, 
I am drafting an IEEE article using rticles and the bookdown referencing. Applying the referencing syntax presented in the bookdown book/snippets found on the internet, threw an error (The LATEX error pointed to a non-defined control sequence. I know too little about LATEX to fix this, nor did I find useful pointers elsewhere.) After updating all packages, the Rmd is knitted but the reference is not replaced but printed, i.e. `\@ref(eq:linear)`.
My unanswered [SO question](https://stackoverflow.com/questions/61247849/rstudio-rticles-knit-to-pdf-book-fails-when-cross-referencing-equations?noredirect=1&lq=1) makes me believe that not many users seem to run into this rticle problem with the IEEE template.

For the time being I draft my paper putting with a placeholder to give me a visual cue at the end to inject the cross-references manually. 
Thanks for providing a pointer how to overcome this and make use of the great bookdown cross-referencing for formulae.

The output of `xfun::session_info('rticles')` is pasted below. With the COVID19 lockdown in full swing, I am unable to test the Rmd on a computer with the latest R and RStudio version. My work laptop requires admin rights for such an update (and I do not have these privileges). Still it feels the error is not package/version related. 

This is the YAML and bookdown reference example for an equation to study the problem

    ---
    title: "rticles fails knitting equation references"
    keywords: ["keyword 1", "keyword 2"]
    abstract: |
         The abstract goes here.
         On multiple lines eventually.
    ## hook up rticles as base format with bookdown for referencing, etc
    output:
      bookdown::pdf_book:
         base_format: rticles::ieee_article
    ---
    
     Introduction
     =============
     
     To add math, I do the following
     See equation \@ref(eq:linear) for more insights.

     \begin{equation}
      a + bx = c  (\#eq:linear)
      \end{equation}
     
     More cool text.

Thanks for any pointer,
Rainer

> xfun::session_info('rticles')
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763), RStudio 1.2.1335

Locale:
  LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
  LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
  LC_TIME=English_United Kingdom.1252    

Package version:
  base64enc_0.1.3 digest_0.6.25   evaluate_0.14   glue_1.4.0      graphics_3.6.1  grDevices_3.6.1
  highr_0.8       htmltools_0.4.0 jsonlite_1.6.1  knitr_1.28      magrittr_1.5    markdown_1.1   
  methods_3.6.1   mime_0.9        Rcpp_1.0.4.6    rlang_0.4.6     rmarkdown_2.1   rticles_0.14.1 
  stats_3.6.1     stringi_1.4.6   stringr_1.4.0   tinytex_0.22    tools_3.6.1     utils_3.6.1    
  xfun_0.13       yaml_2.2.1     

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rticles')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rticles')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by yihui** [comment]
@cderv Could you first verify if the issue is reproducible? Thanks!

**Comment by cderv** [comment]
Thank @rainer-rq-koelle ! I can reproduce and I'll look into it.

**Comment by cderv** [comment]
I think this is because `\eqref` is an unknown command. It is part of the Tex package `amsmath` if I am not mistaken. 
If you add it using yaml header, it will works. (it does for me)
```yaml
output:
  bookdown::pdf_book:
     base_format: rticles::ieee_article
     extra_dependencies: amsmath
```

I think it works by default using bookdown and `pdf_document()` as base format because we depend on pandoc latex template and it is included by default (see [here](https://github.com/jgm/pandoc-templates/blob/490c564f068b65b79bf94119259cbd78bc43f961/default.latex#L100)
 
@yihui I see several solution: 
1. we could consider my answer the official solution
1. we could add it to every rticles template so that they work with bookdown.
1. We could make this addition part of `bookdown::pdf_book` - add `amsmath` (and other required package by bookdown) as `extra_dependencies` for any base format passed to it. I think it is a good idea as it seems there are required tex packages. 

What do you think ? Do you know any other required tex packages for bookdown features to work ?

**Comment by cderv** [comment]
Oh and regarding 1. , I just checked the template: it is intended to use `amsmath` but it is conditional to a variable. 

You need to add 
```yaml
with_amsmath: true
```
in the yaml to activate the use of `amsmath`. I think the skeleton needs to be more documented regarding the options...

**Comment by yihui** [comment]
I'm okay with the additional documentation 69b16fc99b3027fdb73b3aa1e0e83b4de9ec77c6. We might want to enable `amsmath` by default, but I'm not familiar with this journal, so I don't know if it would be a good idea.

Anyway, since the solution seems to be simple enough, I'm going to close this issue for now. Thank you both!

**Comment by rainer-rq-koelle** [comment]
@cderv thanks a lot for your help.
@yihui & @cderv I support the inclusion and support of standard functionality of bookdown referencing across all rticles templates. Equation numbering is a common need. Obviously, my application case is the IEEE template. But I assume other researchers using other templates will benefit from the same set of supported bookdown reference functionality. If 'ansmath' is the fix for the IEEE template, I suppose it will work in other templates as well.
Thanks again for your help in getting me going. Highly appreciated.

**Comment by yihui** [comment]
@rainer-rq-koelle Okay. I just enabled **amsmath** by default in this template. For other templates, it's not clear to me what should be done. Some might have enabled it, and some may not need it. We can deal with the possible problems as they occur. Thanks for the suggestion!

**Comment by cderv** [comment]
@yihui one idea I have: Among `bookdown` features, you have equation referencing. For that you need `\eqref` from **amsmath** otherwise it does not work. As `bookdown::pdf_book` enables to provide any base format, how about insuring that those extra dependencies required for **bookdown** features are passed to the base format (using `extra_dependencies` argument or any other mean ?) ?  Would it be too much ?

At least, we may try to document in **bookdown**, which tex package are required so that the promoting features are working. 

Thoughts ?

**Comment by rainer-rq-koelle** [comment]
@yihui super! Thanks for enabling `amsmath` in rticles IEEE. I am now a "happy camper"! ((just need to find the time to write the paper :) ))
From an end-user perspective +1 for @cderv 's idea of "passing" bookdown feature dependencies to other base formats. That was a bit my problem when the knitting failed. I could not make out why the bookdown equation referecing would throw an error (and then ended up finding no help online). 
It is easy to support this idea from my end-user perspective, as I have no insight in what this means in terms of development or maintenance. Thus, tackling problems as they occur might be the better use of time.

**Comment by yihui** [comment]
I prefer dealing with this problem case by case. Loading LaTeX packages such as **amsmath** automatically could introduce other problems, e.g., users might have loaded the same package with different options via `\usepackage[options]{package}`, which will create conflicts. Therefore I prefer loading as few extra LaTeX packages as possible on my side. Users can load other packages as they need.

**Comment by cderv** [comment]
> users might have loaded the same package with different options

I had not that in mind. It makes complete sense.
