### ISSUE TITLE
missing comma in sage harvard reference style (SAGE template)

### ISSUE THREAD

**Issue by MalteHueckstaedt** [rstudio/rticles#447]
Hello!

I would like to use the SAGE template for submitting an article. Unfortunately, I noticed that the Citation does not conform to the [sage harvard reference style](https://uk.sagepub.com/sites/default/files/sage_harvard_reference_style_0.pdf). Here is an example from the [skeleton](https://github.com/rstudio/rticles/blob/master/inst/rmarkdown/templates/sage/skeleton/skeleton.Rmd) 

<img width="722" alt="Bildschirmfoto 2021-11-18 um 14 00 37" src="https://user-images.githubusercontent.com/47598771/142420071-03531c33-a0c4-414d-a8e5-3ac34443673e.png">

Instead of "last name, comma and year" it cites "last name and year". 

I would appreciate any tips on how to use the template with "last name, comma and year" citation. 

Thanks a lot!

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rticles')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rticles')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
Sage format article is using provided biblio style 
https://github.com/rstudio/rticles/blob/ca8f30f1e2ab31b75e87080356176e602733e084/inst/rmarkdown/templates/sage/resources/template.tex#L82-L85

which is passed through YAML
https://github.com/rstudio/rticles/blob/ca8f30f1e2ab31b75e87080356176e602733e084/inst/rmarkdown/templates/sage/skeleton/skeleton.Rmd#L26

This is because this formats seems to use `natbib` only for bibliography. 

According files are provided with the format and maybe those files are out of date and needs updating ? 

You can try find another bst file for this biblio style and see if it changes something. 

@oguzhanogreden contributed the format. Do you have insight here @oguzhanogreden ? 

We would need to go through the guideline and update the journal template accordingly;

One option is also to not rely on natbib only but allow to use the Pandoc citation processing which could use CSL. It seems there is a CSL for Sage harvard style : https://www.zotero.org/styles?q=Sage%20-%20Harvard

**Comment by MalteHueckstaedt** [comment]
thank you @cderv,

another simple workaround is to put the following LaTex line after the YAML:

```latex
\setcitestyle{aysep={,}}
```

**Comment by oguzhanogreden** [comment]
I don't have anything to contribute to this discussion, unfortunately. 

It's been a long time since I've quit academia and academic writing.

**Comment by cderv** [comment]
@MalteHueckstaedt do you think we should add this in the template directly ? Is this required per guidelines ?

**Comment by MalteHueckstaedt** [comment]
@cderv, yes, i think the guideline of [sage harvard reference style](https://uk.sagepub.com/sites/default/files/sage_harvard_reference_style_0.pdf) clearly requires the comma between author and year. 

In fact, the line`\setcitestyle{aysep={,}}` can simply be inserted into the [template](https://github.com/rstudio/rticles/blob/master/inst/rmarkdown/templates/sage/resources/template.tex) at line 51 and the problem is solved.

https://github.com/rstudio/rticles/blob/08d75eb3067425cc442ed3706bda6ee68ba2a2e3/inst/rmarkdown/templates/sage/resources/template.tex#L50-L52

This would go just like that:

```diff
\begin{document}

+ \setcitestyle{aysep={,}}

\title{$title$}
```
Should I make a pull request?

**Comment by cderv** [comment]
@MalteHueckstaedt yes please do. 

Thanks a lot for this solution !

**Comment by MalteHueckstaedt** [comment]
done: https://github.com/rstudio/rticles/pull/451
