### ISSUE TITLE
Make orcidlink.sty inclusion in JSS template conditional

### ISSUE THREAD

**Issue by Enchufa2** [rstudio/rticles#512]
Please allow me to revisit this issue (#493, #495), because since the introduction of the ORCiD feature in #465, we have been experiencing warnings on CRAN for macOS machines. See e.g. [this](https://cran.r-project.org/web//checks/check_results_simmer.html). So far I haven't received any ultimatum from CRAN, but I suspect that this would bite at some point. So I would like to propose to make the inclusion of ORCiD links conditional to the presence of this package (e.g. via `\IfFileExists{}{}`).

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rticles')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rticles')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
I am ok to make this package optional, but to clarify, we are using the JSS template as base (the one from https://www.jstatsoft.org/style) which includes orcidlink usage. Making it conditional in our template, means there will be one more manual step when we update. I would suggest you do a PR and if this is simple enough conditional then I'll consider merging. Basically, what would make sense considering Pandoc's template would be to only load the package when `orcid` is used as an author field (this is when `\orcidlink{}` command is needed and the package needs to be loaded)

For this one change I guess it is possible, but there could be other issues later on as in your case the real issue is that CRAN servers do not have all the LaTeX requirement available to build JSS tex template. Hopefully, orcidlink in the only issue.

**Comment by Enchufa2** [comment]
I see. Let me ask on CRAN then whether they are willing to add this file to those machines.

**Comment by cderv** [comment]
Great - good idea ! Thanks for willing to do that. 

I really don't know how they handle (or want to handle) TeX dependencies from CTAN. the sty file needed here is from CTAN package https://ctan.org/pkg/orcidlink that they would need to make available

**Comment by Enchufa2** [comment]
From Simon Urbanek:

> Ok, I have bumped TL to 2022 on arm64 and just installed orcidlink it by hand on x86_64 since we don't have enough disk space to do both there, so hopefully next builds should not issue that warning.

So we can close this.

**Comment by cderv** [comment]
Awesome ! thanks for the update on this !
