### ISSUE TITLE
RJournal.sty: No section numbering

### ISSUE THREAD

**Issue by zeileis** [rstudio/rticles#517]
---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rticles')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rticles')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

---

The version of the `RJournal.sty` shipped with `rticles` differs from the one shipped with `rjtools` regarding the section numbering. `rticles` has no section numbers while `rjtools` has. See line 106 in the files:

https://github.com/rstudio/rticles/blob/main/inst/rmarkdown/templates/rjournal/skeleton/RJournal.sty#L106
https://github.com/rjournal/rjtools/blob/main/inst/tex/RJournal.sty#L106

Apparently, the section numbering was added for the LaTeX/PDF version when setting up the HTML version for R Journal articles, see: https://github.com/rjournal/rjtools/commit/c07c4590d53d45a85ef2d5506e4ced42f8dbcc93

I'll also report this to the `rjtools` authors.

**Comment by cderv** [comment]
Hi ! 

@mitchelloharawild is the `.sty` file contain in rjtools the official one now ? 

**rticles** is based of the one provided inside the Zip latex folder available at https://journal.r-project.org/submissions.html#traditional-latex-format

And it has 
````latex
\usepackage[medium]{titlesec}
\usepackage{titletoc}
\titleformat{\section}   {\normalfont\large\bfseries}{}{0em}{}
\titleformat{\subsection}{\normalfont\normalsize\bfseries}{}{0em}{}
\titlecontents{chapter}   [0em]{}{}{}{\titlerule*[1em]{.}\contentspage}
````

It seems it was tweak in rjtools but not fixed in other template. https://github.com/rjournal/rjtools/commit/c07c4590d53d45a85ef2d5506e4ced42f8dbcc93

PR still open at https://github.com/rjournal/rjournal.github.io/pull/75

I will port the change but this raises the question of your comment, but you never opened an issue in this repo to ask us
> I am unsure if they plan to continue providing the rjournal article format in their package as we encourage submissions in the rjtools HTML/PDF format.

I am ok with adding a deprecation warning inside **rticles** package to explain that now **rjtools** should be used. Initially we did the format as there was none, there is no point in keeping it inside **rticles** if it is not to be used to submit to R Journal

What should we do about this ?
