### ISSUE TITLE
moving to Quarto?

### ISSUE THREAD

**Issue by pachadotdev** [rstudio/rticles#537]
IDK if there are plans for this, but I started moving it to Quarto here https://github.com/pachadotdev/rticles2

**Comment by cderv** [comment]
Can you detail what you mean by  "Moving to Quarto" ? 

It seems you want a R package like **rticles** but using quarto under the hood, is that so ? 

Regarding Quarto output for Journals, this is something we thought about from the start. 

Journals template are part of Quarto output formats as shown in https://quarto.org/docs/extensions/listing-journals.html
This page contains a list of journals we started to offer a template.  They live in the organization https://github.com/quarto-journals
How to create format is described at https://quarto.org/docs/journals/formats.html

We did not plan for a R package **rticles2** for this because 

* Quarto aims to offer output format for all users, and not just R users. The Journals Articles specific format can be used with Quarto no matter the tooling (no computation, knitr computation, Jupyter computation). 

* Quarto format are not developed in R and the templating system for LaTeX is improved (using partials). So using custom Quarto format is better.

* Extension mechanism does not require a R package to be available to use it. 


We are happy to receive contribution to port new format to Quarto Journals organization from those available in **rticles**

Also happy to discuss what you have in mind with **rticles2** 

* Does this need to be a fork of this project ? 
* What is the purpose of having a '<nameofpackage>2'  package ? Usually this is for a complete rewrite on new grounds (like httr -> httr2) ?  What would it be for **rticles** ? 

Thanks.

**Comment by pachadotdev** [comment]
Thanks. My idea was to move all the templates and simplify a bit.

**Comment by cderv** [comment]
This is more than welcome ! Were you planning to work on a specific template ? 

There should be one Format extension available for each, with using partials to modify the default template accordingly, and setting some YAML options to tweak the default. 

There is already a few examples of templates (that could also need improvment). I am happy to review and help you get started on any of those.

**Comment by pachadotdev** [comment]
thanks a lot! I'll send you a draft once I have simplified the Elsevier templates

**Comment by cderv** [comment]
Just a head up that we have a elsevier version at https://github.com/quarto-journals/elsevier 

Please feel free to send PR if it misses some feature and / or need some improvements.
