### ISSUE TITLE
Taylor & Francis Reference Style needs updating

### ISSUE THREAD

**Issue by ehsanx** [rstudio/rticles#556]
Taylor & Francis Reference Style is different from the one provided by rticles::tf_article

The current rticles::tf_article provides the following in the tex file:
\usepackage{natbib}% Citation support using natbib.sty
\bibpunct[, ]{(}{)}{;}{a}{}{,}% Citation support using natbib.sty

However, as per https://files.taylorandfrancis.com/tf_S.pdf it should be simply
\usepackage[numbers]{natbib}

----

R version 4.3.0 (2023-04-21 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621), RStudio 2023.12.0.369

Locale:
  LC_COLLATE=English_Canada.utf8  LC_CTYPE=English_Canada.utf8    LC_MONETARY=English_Canada.utf8
  LC_NUMERIC=C                    LC_TIME=English_Canada.utf8    

time zone: America/Vancouver
tzcode source: internal

Package version:
  base64enc_0.1.3   bslib_0.5.1       cachem_1.0.8      cli_3.6.1         digest_0.6.31    
  ellipsis_0.3.2    evaluate_0.23     fastmap_1.1.1     fontawesome_0.5.2 fs_1.6.3         
  glue_1.6.2        graphics_4.3.0    grDevices_4.3.0   highr_0.10        htmltools_0.5.5  
  jquerylib_0.1.4   jsonlite_1.8.7    knitr_1.45        lifecycle_1.0.4   magrittr_2.0.3   
  memoise_2.0.1     methods_4.3.0     mime_0.12         R6_2.5.1          rappdirs_0.3.3   
  rlang_1.1.1       rmarkdown_2.25    rticles_0.25      sass_0.4.7        stats_4.3.0      
  stringi_1.7.12    stringr_1.5.0     tinytex_0.48      tools_4.3.0       utils_4.3.0      
  vctrs_0.6.4       xfun_0.39         yaml_2.3.7
---

By filing an issue to this repo, I promise that

- [ x] I have fully read the issue guide at https://yihui.name/issue/.
- [ x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rticles')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rticles')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [ x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
Thanks for opening an issue. 

It seems indeed there was an update in the templates we can find at : https://files.taylorandfrancis.com/InteractCADLaTeX.zip

````latex
% interactcadsample.tex
% v1.04 - May 2023

\documentclass[]{interact}

\usepackage{epstopdf}% To incorporate .eps illustrations using PDFLaTeX, etc.
\usepackage{subfigure}% Support for small, `sub' figures and tables
%\usepackage[nolists,tablesfirst]{endfloat}% To `separate' figures and tables from text if required

\usepackage{natbib}% Citation support using natbib.sty
\bibpunct[, ]{(}{)}{;}{a}{}{,}% Citation support using natbib.sty
\renewcommand\bibfont{\fontsize{10}{12}\selectfont}% Bibliography support using natbib.sty
````

But the `bibpunct` line is still there. 

I can do the update for the template, but still this line would be there. 

For which journal https://files.taylorandfrancis.com/tf_S.pdf ? maybe they use another template ?

**Comment by cderv** [comment]
I have updated to latest file from bundle linked. 

Please do share any other T&F template that may not be compatible with this one. 

It was initially added in #218 by @dleutnant and may not cover all the possible Journals

**Comment by ehsanx** [comment]
> For which journal https://files.taylorandfrancis.com/tf_S.pdf ? maybe they use another template ?

I received it from the "Journal of Applied Statistics".

**Comment by cderv** [comment]
So this one: https://www.tandfonline.com/journals/cjas20

From their instruction (https://www.tandfonline.com/action/authorSubmission?show=instructions&journalCode=cjas20) they have other template available at https://files.taylorandfrancis.com/InteractTFSLaTeX.zip

This templates does have 
 ````

\usepackage[numbers,sort&compress]{natbib}% Citation support using natbib.sty
\bibpunct[, ]{[}{]}{,}{n}{,}{,}% Citation support using natbib.sty

**Comment by cderv** [comment]
Something does not seem to work ok with `tfs.bst` provided in the template... So it needs more work. 

You have the PR linked if you want to try and help adapt

**Comment by rlaboiss** [comment]
The situation is more complex than described in the present issue. Taylor & Francis provides other templates besides the Chicago author-date (originally include in rticles) and the S template mentioned above. I found the templates listed below, along with the associated ZIP file, provided by T&F. I do not know if this list is exhaustive. The LaTeX sample files `interact*sample.tex` in these templates differ from each other. The ZIP tarballs contain different `interact.cls` files and, of course, the `interact*sample.tex` files vary as regards the argument of the `\bibliographystyle` command.

- APA [(InteractAPALaTeX.zip](https://files.taylorandfrancis.com/InteractAPALaTeX.zip))
    - `interact.cls` v1.05
    - `interactapasample.tex` template provided
    - `\bibliographystyle{apacite}`
- Chicago AD [(InteractCADLaTeX.zip](https://files.taylorandfrancis.com/InteractCADLaTeX.zip))
    - `interact.cls` v1.03
    - `interactcadsample.tex` template provided
    - `\bibliographystyle{tfcad}` (file `tfcad.bst` provided)
- NLM [(InteractNLMLaTeX.zip](https://files.taylorandfrancis.com/InteractNLMLaTeX.zip))
    - `interact.cls` v1.05
    - `interactnlmsample.tex` template provided
    - `\bibliographystyle{tfnlm}` (file `tfnlm.bst` provided)
- P [(InteractTFPLaTeX.zip](https://files.taylorandfrancis.com/InteractTFPLaTeX.zip))
    - `interact.cls` v1.01
    - `interacttfpsample.tex` template provided
    - `\bibliographystyle{tfp}` (file `tfp.bst` provided)
- Q [(InteractTFQLaTeX.zip](https://files.taylorandfrancis.com/InteractTFQLaTeX.zip))
    - `interact.cls` v1.05
    - `interacttfqsample.tex` template provided
    - `\bibliographystyle{tfq}` (file `tfq.bst` provided)
- S [(InteractTFSLaTeX.zip](https://files.taylorandfrancis.com/InteractTFSLaTeX.zip))
    - `interact.cls` v1.05
    - `interacttfssample.tex` template provided
    - `\bibliographystyle{tfs}` (file `tfs.bst` provided)


I am aware of issue #321, where the adaptation to the APA style has been discussed. The ideal solution would be to generalize the approach in PR #557. However, besides the appropriate argument for the `\bibliograpystyle` command, the `interact.cls` should be select among the version 1.01, 1.03, and 1.05 (see above) and the appropriate `interact*sample.tex` should be selected according to the desired reference style specified by the user. 

I could try to propose a PR for this, but I am afraid I konw very little from the internals of rticles.

**Comment by cderv** [comment]
Thanks a lot for all this listing. It seems indeed more complex 🤔 

> I could try to propose a PR for this, but I am afraid I konw very little from the internals of rticles.

Internal is not that hard, and I can help with that or adapt from where you have something working. We don't have a few example though where one article function handle several template... Usually it is one function = one template. So the decision will be about: is this possible to make a single template configurable enough. 

Example for the latter is 
- `oup_article()` was a format we needed to handle an upgrade with totally differente template. So it shows what we've done. 
- Some function have a `journal` argument to conditionally change some stuff for the template like `ims_article`, `joss_article`, `oup_article`, ...

If you spend some time looking at complex journal function we have, it would be a good example to see what is done usually. 

However, if you have a design in mind, and would know what needs to differ between those templates, I can guide during the PR. Help very welcome on this TBH ! 

Some hints based on your comments

> The ZIP tarballs contain different interact.cls files and, of course, the interact*sample.tex files vary as regards the argument of the \bibliographystyle command.

It seems we need to store all class files in the **rticles** package, and somehow rename / move it when installing. This is not ideal in current design as usually we have a folder we move to the project without change... So either we have different template with each there class file, or we make an exception with a new design to "install" the right version depending of the template. Or use the right version from the .tex file. Unless we named same with there version number, but this would modify the template .tex file I think

For the bibliostyle, this is definitly something that is configurable using R argument, and then pass the variable for the template. In this function for example, we build arguments to pass to the template
https://github.com/rstudio/rticles/blob/1aee9911a3c205e2434f6fba0259396526ea59b4/R/joss_article.R#L20-L40

So to me this is the hard part...
> the interact.cls should be select among the version 1.01, 1.03, and 1.05 (see above)

Is there a reason they don't use the same ? Is that because template are not up to date and they should use it ? Or should we really maintain version difference ? 

Thanks a lot

**Comment by rlaboiss** [comment]
Thank you for your thorough comments. I may try to propose a PR along the lines you suggested.

> So to me this is the hard part...
> 
> > the interact.cls should be selected among the version 1.01, 1.03, and 1.05 (see above)
> 
> Is there a reason they don't use the same ? Is that because template are not up to date and they should use it ? Or should we really maintain version difference ?

I have no idea about the answers to these questions. Perhaps, everything would be fine with the latest version of `interact.cls` (1.05).

A very simple way to cope with the problem would be to create separate functions (and separate template directories) for each reference style, namely`tf_apa`, `tf_cad`, `tf_nlm`, `tf_tfp`, ` tf_tfq`, and `tf_tfs`, with `tf_article` as an alias to `tf_cad`, for backward compatibility. I admit that this solution is pretty cumbersome, since there will be many duplicated files everywhere.

Another solution would be to allow the specification of which files under `rmarkdown/templates/tf/skeleton/` should be copied, according to the user's choice. However, it seems that this is under the responsibility of `rmarkdown::draft` and is beyond the scope of rticles.

A feasible solution would be to add all versions of `interact.cls`, eventually renaming them to `interact-v1.01.cls`, `interact-v1.03.cls`, and `interact-v1.05.cls` and ship an `intercat.cls` file that use some TeX logic to `\include`  the appropriate `.cls` file. Also, all the `tf_*.bst` would be included in the `skeleton` directory, with some Pandoc conditional logic around the `\bibliographystyle` command. This solution would have two drawbacks: first, the `template.tex` would be complex, including lots of conditionals for the different reference styles, and, second, the user will get a lot of useless files installed along their draft.

**Comment by cderv** [comment]
> A very simple way to cope with the problem would be to create separate functions (and separate template directories) for each reference style, namelytf_apa, tf_cad, tf_nlm, tf_tfp,  tf_tfq, and tf_tfs, with tf_article as an alias to tf_cad, for backward compatibility. I admit that this solution is pretty cumbersome, since there will be many duplicated files everywhere.

Definitely, but we have a duplication problem for sure. CRAN package size are limited so I need to keep the size of the package under contraints too. 

> Another solution would be to allow the specification of which files under rmarkdown/templates/tf/skeleton/ should be copied, according to the user's choice. However, it seems that this is under the responsibility of rmarkdown::draft and is beyond the scope of rticles.

Yes exactly. We are tied by `draft()` design here. 

> A feasible solution would be to add all versions of interact.cls, eventually renaming them to interact-v1.01.cls, interact-v1.03.cls, and interact-v1.05.cls and ship an interact.cls file that uses some TeX logic to \include the appropriate .cls file.

This would be possible, but the .tex file produced needs to be compatible with the expectation of the journal. I wonder if they would accept modified .tex content like this to comply with our problems ? 🤔 

Maybe there is a middle option where could have one template folder with all resource except the class file, and the correct cls file would be copied into directory at render time - right before rendering with pandoc and dependending on the article function used ? 

Usually we do copy everything at draft building but maybe we can make an exception here, and copy only when used so .cls and .bst as we don't know beforehand which one is needed. 

I could also see if there is an adjustement without breaking change I could make in `rmarkdown::draft()` that would help with this case... I need to check that RStudio IDE is indeed using `draft()` too so that those template can work in the menu to create new template.

**Comment by rlaboiss** [comment]
> I could also see if there is an adjustement without breaking change I could make in `rmarkdown::draft()` that would help with this case... I need to check that RStudio IDE is indeed using `draft()` too so that those template can work in the menu to create new template. 

If you can change `rmarkdown::draft()`, it will be great. It should be okay, in terms of backward compatibility, if you added an argument for specifying the list of extra files to be installed.

**Comment by rlaboiss** [comment]
> > I could also see if there is an adjustement without breaking change I could make in `rmarkdown::draft()` that would help with this case... I need to check that RStudio IDE is indeed using `draft()` too so that those template can work in the menu to create new template.
> 
> If you can change `rmarkdown::draft()`, it will be great. It should be okay, in terms of backward compatibility, if you added an argument for specifying the list of extra files to be installed.

Any news about this?

I need to prepare a manuscript for publication in a Taylor & Francis journal, which uses the InteractAPA style. Is there a simple way to change the template used by `rmarkdown::render`?

**Comment by rlaboiss** [comment]
> I need to prepare a manuscript for publication in a Taylor & Francis journal, which uses the InteractAPA style. Is there a simple way to change the template used by `rmarkdown::render`?

Waiting for the fix for the issue in question, I got around my problem of using `apacite` with `tf_article`. I describe my solution below, in case someone stumbles over the same problem.

1. Copy the template `rticles/rmarkdown/templates/tf/resources/template.tex` into the same directory as the source `.Rmd` file and apply the following patch to it:
```
--- template-tf-article.tex	2024-11-26 08:14:45.751008046 +0100
+++ template.tex	2024-11-26 07:49:53.000000000 +0100
@@ -7,9 +7,9 @@
 \usepackage{subfigure}% Support for small, `sub' figures and tables
 %\usepackage[nolists,tablesfirst]{endfloat}% To `separate' figures and tables from text if required
 
-\usepackage{natbib}% Citation support using natbib.sty
-\bibpunct[, ]{(}{)}{;}{a}{}{,}% Citation support using natbib.sty
-\renewcommand\bibfont{\fontsize{10}{12}\selectfont}% Bibliography support using natbib.sty
+\usepackage[natbibapa]{apacite}% Citation support using apacite.sty. Commands using natbib.sty MUST be deactivated first!
+\setlength\bibhang{12pt}% To set the indentation in the list of references using apacite.sty. Commands using natbib.sty MUST be deactivated first!
+\renewcommand\bibliographytypesize{\fontsize{10}{12}\selectfont}% To set the list of references in 10 point font using apacite.sty. Commands using natbib.sty MUST be deactivated first!
 
 \theoremstyle{plain}% Theorem-like structures provided by amsthm.sty
 \newtheorem{theorem}{Theorem}[section]
```
2. In the YAML header of the `.Rmd` file, use:
```
biblio-style: apacite
output: function(){t<-rticles::tf_article();t$pandoc$args[4]<-"template.tex";t}
```
3. Replace the `interact.cls` file installed by `rmarkdown::draft` by the one provided in [InteractAPALaTeX.zip](https://files.taylorandfrancis.com/InteractAPALaTeX.zip).

I admit that it is hacky, but it works for me.™

**Comment by cderv** [comment]
> Any news about this?

Quarto 1.6 is now release (yesterday) so I am getting back to this package for an update. I'll look at `draft()` but I admit last time I did try to improve it for `oup_article()` I did not found an easy way. 

i'll revisit. Though glad you found a solution in the meantime. 

> output: function(){t<-rticles::tf_article();t$pandoc$args[4]<-"template.tex";t}

I would have expected that the template could be replaced directly 

````
output:
  tf_article:
    template: patch-template.tex
````

Is this not working ?

**Comment by rlaboiss** [comment]
> I would have expected that the template could be replaced directly
> 
> ```
> output:
>   rticles::tf_article:
>     template: patch-template.tex
> ```
> 
> Is this not working ?

Yes, it does. Thanks!

**Comment by rlaboiss** [comment]
I investigate further the issue regarding the different version of `interact.cls`. Just for recollection's sake, this is the situation:
- APA: v1.05
- TFP: v1.05
- TFQ: v1.05
- TFS: v1.05
- CAD: v1.03
- NLM: v1.01

I compiled the `interact*sample.tex` examples provided by Taylor & Francis for the CAD and NLM cases with version v1.05 of `intercat.cls`. Everything went fine. I compared the output PDF files using the [diff-pdf](https://vslavik.github.io/diff-pdf/) command, and it seems that the differences are minimal, essentially in white spacing.  Here is an example:
![Image](https://github.com/user-attachments/assets/6d4ae903-6e2e-4e61-9e17-d6df8829924d)

So, I can confidently tell that v1.05 will be appropriate for all articles submitted to T&F journals. This removes one of the complications of the present issue.

Now, regarding the `interact*sample.tex` templates provided by T&F, it seems that they do not differ a lot from `inst/rmarkdown/templates/tf/resources/template.tex`, in terms of the preamble material. The main difference is related to which bibliography style is chosen.

Considering all that, I prepared PR #581 as a first attempt to fix the current issue. There are still two remaining problems:
1. The skeleton file `inst/rmarkdown/templates/tf/skeleton/skeleton.Rmd` still contains references to the Chicago Author-Date reference style.
2. File `inst/rmarkdown/templates/tf/skeleton/interactcadsample.bib` still contains “cad” in its name.
3. All files `inst/rmarkdown/templates/tf/skeleton/tf{cad,nlm,p,q,s}.bst` get installed when creating a draft.

**Comment by rlaboiss** [comment]
I did an extra commit (8ecb69ca27adb4ab2f9d47fdf50189c5c4404c7e) in PR #581, to fix the problem of an absent `biblio-style` header in the YAML header.

I have two remaining questions:
1. The `pre_knit` definition of the `springer_article` function (from which I took inspiration for writing my changes in `tf_article`) has `return(invisible(NULL))` at its end. Is that mandatory for `pre_knit` definitions?
2. I am currently using `\ifboolexpr` and `\ifstrequal` logic in `template.tex`. I did it because it seems that pandoc template conditionals do not support constructs like `$if(variable = value)$`. However, it may be possible to do the logic in `tf_article` (via `pandoc_args`) instead of overloading `template.tex` (and, so, making the final user's TeX file less complex). Do you think that the former method should be used ?

**Comment by rlaboiss** [comment]
> 2. I am currently using `\ifboolexpr` and `\ifstrequal` logic in `template.tex`. I did it because it seems that pandoc template conditionals do not support constructs like `$if(variable = value)$`. However, it may be possible to do the logic in `tf_article` (via `pandoc_args`) instead of overloading `template.tex` (and, so, making the final user's TeX file less complex). Do you think that the former method should be used ?

I went ahead and pushed the commit a1774b481edba5b223ba6ed25906ef81f94990b2, in which the `pre_knit` approach is replaced by the approach using `pandoc_args`. With this change, instead of using the field `biblio-style` in the YAML header, users should specify the T&F bibliography style like this:

```yaml
output:
  rticles::tf_article:
    biblio_style: APA
```

This simplifies the code in `template.tex`, which has now:

```
$if(bibliography)$
\bibliographystyle{$bst-name$}
\bibliography{$bibliography$}
$endif$
```

There is still a convoluted logic using `\ifboolexpr` and `\ifstrequal` in the preamble of `template.tex`, though.

**Comment by rlaboiss** [comment]
I have looked at all the six sample files provided by Taylor & Francis (`interactapasample.tex`, `interactcadsample.tex`, `interactnlmsample.tex`, `interacttfpsample.tex`, `interacttfqsample.tex`, and `interacttfssample.tex`). I pushed the commit eab22c52, in which the file `skeleton.Rmd` is adapted, accordingly.

Furthermore, I still have to adapt the sections “References cited in the text” and “The list of references” in `skeleton.Rmd`. This will be tricky, because there are specific `\cite*` commands that are used for each of the references styles.

Anyway, I am making progress.

**Comment by rlaboiss** [comment]
> Furthermore, I still have to adapt the sections “References cited in the text” and “The list of references” in `skeleton.Rmd`. This will be tricky, because there are specific `\cite*` commands that are used for each of the references styles.

This has been done in commit 11dc4eb5 (with some improvements done in the subsequent commits).

I have tested my changes with all possible reference styles required by Taylor & Francis (APA, CAD, NLM, TFP, TFQ, and TFS). Everything seems to work fine. I think that the PR #581 is now ready for review. There is only an annoying point: all `tf*.bst` are installed by 

I guess that, in case my PR get merged, my name will appear in the `DESCRIPTION` file. Please, tell me which role should I indicated for myself. Another question: Should I add my name and affiliation in the YAML header of `inst/rmarkdown/templates/tf/skeleton/skeleton.Rmd`?

**Comment by rlaboiss** [comment]
In commit dfca82774dfd9bd9240a6217e2c4a11f582f6399, I changed the convoluted code using `\ifstrequal` and `\ifbollexpr` in `template.tex` to a code using lists in `tf_article()`. This can be reverted, if it is not appropriate, but I think this is a reasonable change for two reasons. First, the user is expected to send the generated .tex file to the publisher for publication, and it is better to have that file cleaner. Second, the code now is more readable and maintainable.

The drawback is that the `tf_article` function became pretty long. Should it be moved into a separate file, like `oup_article.R`?

**Comment by rlaboiss** [comment]
For anyone lurking here, interested in trying out my changes, just run the following code in R or in RStudio:

```r
install.packages("devtools")
library(devtools)
install_github("rlaboiss/rticles@taylor-and-francis")
```

**Comment by cderv** [comment]
Sorry to not have looked at all this before ! Reviewing the PR now. Thanks @rlaboiss !

**Comment by rlaboiss** [comment]
Thanks for you comments on my  @cderv. I will take a look at them as soon as possible.

**Comment by rlaboiss** [comment]
@cderv: I think I addressed all the issues that you raised in your review of my commits in PR #581. The only “contentious” point concerns the deprecation of the `biblio_style` field in the YAML header. I am not 100% sure you agree with my design.

Otherwise, could you please review the commit 0b368f1e486a04f613759d4673b28088430e0104? After I pushed it, I am having trouble to install the package via `install_github`:
```
Rscript -e 'devtools::install_github("rlaboiss/rticles", upgrade = FALSE)'
Error: Failed to install 'unknown package' from GitHub:
  Line starting 'Roxyge ...' is malformed!
```

**Comment by rlaboiss** [comment]
> Otherwise, could you please review the commit [0b368f1](https://github.com/rstudio/rticles/commit/0b368f1e486a04f613759d4673b28088430e0104)? After I pushed it, I am having trouble to install the package via `install_github`:
> 
> ```
> Rscript -e 'devtools::install_github("rlaboiss/rticles", upgrade = FALSE)'
> Error: Failed to install 'unknown package' from GitHub:
>   Line starting 'Roxyge ...' is malformed!
> ```

I investigated the issue and discovered that the culprit is the accented letter in my family name. When I use Unicode escaping, changing `"Laboissière"` to `"Laboissi\u00e8re"` (commit e0b8e90bab8799ad5303aa48bc8ea783f347da2f), it works. This is strange, since there is already another author listed in `DESCRIPTION` whose name contains Unicode characters (Oğuzhan Öğreden).

**Comment by cderv** [comment]
@rlaboiss I did not manage to reproduce the installation problem. 

This is merged with putting back the accented character. 
Can you try again with  
````r
devtools::install_github('rstudio/rticles', upgrade = FALSE)
````

I'll revert to using `\u00e8` otherwise, thanks

**Comment by rlaboiss** [comment]
> [@rlaboiss](https://github.com/rlaboiss) I did not manage to reproduce the installation problem.
> 
> This is merged with putting back the accented character. Can you try again with
> 
> devtools::install_github('rstudio/rticles', upgrade = FALSE)
> I'll revert to using `\u00e8` otherwise, thanks

I should have given more context on my issue. It arose in a very specific context, namely in the generation of a docker image with the rticles package pre-installed via `remotes::install_github`.  The problem probably comes from one of the pre-installed Debian packages. I fixed the problem by using `pak::pkg_install`, instead.

Thanks anyway for your concern.
