### ISSUE TITLE
Specify journal in Elsevier YAML

### ISSUE THREAD

**Issue by frenchja** [rstudio/rticles#66]
Feature Request:  We could allow the author to specify which journal they've submitted the preprint to in the RMarkdown YAML, instead of hard coding it to Elsevier: 

https://github.com/rstudio/rticles/blob/90286b14141b957b68b3db6b5d0a5eafefb1e4ce/inst/rmarkdown/templates/elsevier_article/skeleton/elsarticle.cls#L398

**Comment by jjallaire** [comment]
If you are motivated to get these changes in I suggest either a PR or contact the original author of the Elsevier format (@cboettig) to see if they are willing to make the enhancements (we don't actively maintain formats that are contributed).

**Comment by cboettig** [comment]
@frenchja Thanks for the suggestion.  Unfortunately as you see, Elsevier chose not to make that a configurable option in their `tex` template -- that's hard-coded in the `cls` file by Elsevier.  You should feel free to modify that class file in your own use, but rmarkdown/pandoc don't provide a way to customize class files with yaml (since they aren't meant to be customized in that way anyhow).  There is probably some clever override you could add to your tex header (which rmarkdown does support).

@jjallaire feel free to close this since I don't think it's immediately actionable.

**Comment by yihui** [comment]
Fixed via #152.
