### ISSUE TITLE
pnas reference encoding

### ISSUE THREAD

**Issue by paleo13** [rstudio/rticles#77]
Hi @cboettig and the rstudio team,

When using the PNAS template, the references in the output .tex file are encoded using \hypertarget and not using \bibitem ([as required in the submission guidelines](http://www.pnas.org/site/misc/PNASDOCS.PDF)). 

Could this please be fixed? It seems like the conversion from .Rmd to .md to .tex to .pdf occurs in a single run of  pandoc. 

At the moment, I'm trying to use an R script to modify the .tex file output during this process, and then rerunning pandoc to generate the pdf.

**Comment by paleo13** [comment]
Currently, I'm using the following command (in ubuntu) to turn the .tex file into a .pdf. 

```
/usr/bin/pandoc +RTS -K512m -RTS article.tex -o article.pdf --latex-engine pdflatex --include-in-header preamble.tex
```
However,  it seems to be ignoring the pnas class and style files, and generating a pdf file that has normal latex formatting. I have copied all the pnas style and class files into the same directory as the .tex file

Any advice on how to fix this? Also, let me know if this would be more appropriate on stack overflow.

**Comment by cboettig** [comment]
If you want to keep the intermediate Tex file you can simply add `keep_tex: true` in the tank header, just like rmarkdown's standard PDF format (see the docs for details).

As to the bibentry format, I believe you'll have to take that up with pandoc; what you see is how pandoc handles references (note that pandoc uses csl instead of bst for formatting and refs need not come in bibtex files).  You can work around this easily enough however by just writing your references in with a straight up LaTeX (e.g. `\cite` etc and specify the bst file etc and run bibtex).  It will mean you cannot also generate HTML via pandoc from the same Rmd file, but that probably doesn't matter much in this use case.

Happy to hear suggestions from others, but to my knowledge there isn't a way to make pandoc output refs in bibitem format .  Maybe a query to the pandoc lists on that issue might provide some better ideas.  

Thanks for the comments and other issues always welcome if we can improve the template.

**Comment by paleo13** [comment]
Thanks for getting back to me so quickly.

Yeah, I'm using that option to retain the .tex file.

Thanks for confirming there's probably not a way to tell pandoc to use bibitem's, so I'll concentrare my efforts on modifying the .tex file and then remaking the .pdf

So, I'm running this command in bash to generate the .tex file and an initial .pdf file

```
R -e "rmarkdown::render('code/rmarkdown/article.Rmd')"
```

then I'm running this command to modify the reference format

````
R -e "source('code/R/functions/format_pnas.R');format_pnas('code/rmarkdown/article.tex','code/rmarkdown/article.tex')"
```

then I'm running this command to remake the .pdf using the modified .tex file 

```
cd code/rmarkdown && /usr/bin/pandoc +RTS -K512m -RTS article.tex -o article.pdf --latex-engine pdflatex --include-in-header preamble.tex && cd ../..
```

After that, pandoc generates a .pdf file,  but it doesn't have the pnas formatting. Am I missing any pandoc flags?

**Comment by cboettig** [comment]
Looks like you haven't used the `--template` flag, among others.  Take a look at the pandoc commands echoes by rmarkdown when it builds the PDF.

**Comment by paleo13** [comment]
Thanks, I realized I should just use `pdflatex` to compile the final .pdf after generating the .tex file
