### ISSUE TITLE
PNAS template - rendering materials and methods

### ISSUE THREAD

**Issue by mcfrank** [rstudio/rticles#84]
Thanks for the template - it's very useful! It's not clear from the template or instructions how to use the "materials and methods" section, though. Minimally, it'd be nice to document that \matmethods{ABC} produces that section. But this functionality is hard to use because markdown syntax doesn't render within \matmethods, e.g. citations are not possible.

**Comment by cboettig** [comment]
@mcfrank Correct, as far as I can tell there's no nice way to handle these structures when using the LaTeX document as a template (after all, *.tex files were never meant to be template style files).  I'm not really sure what is best to recommend here, I see a few options:

1. Tell the user to include the `tex` commands in their methods section.  I think this means that everything in the section needs to be written in tex style rather than pandoc-markdown (citations, tables, equations, section references, etc), since pandoc won't parse stuff inside of a latex argument.  

1. I tried redefining the `\matmethods{}` to behave more like an environment (e.g. `\begin{matmethods}` so that pandoc would then still render markdown inside it, but I didn't have any luck with this.  If anyone gets that to work, a PR would be great.

1. Make the methods section something that comes from the yaml, like the other smaller sections on COI, author contribution, abstract etc.  This is probably no good since references, math and the like wouldn't work.  

1. Just ignore the `matmethods{}` call and just write the methods at the end using the default styling.  Of course you don't get the slightly smaller font that methods are supposed to be written in, but you still get something that looks close enough to have a good estimate of page length I think.  After all, I don't believe PNAS cares about the tex for the final submission; they rip the text out and re-render in their system anyhow.

I lean towards the last option, bit would love to hear from other users battling with the template what route is best and how and where to document it. (e.g. in the R documentation or just in comments on the skeleton .Rmd file?)

**Comment by mcfrank** [comment]
I think (4) is a good choice, though you could provide some kind of hack for styling with a smaller font. I tried just adding `/small`, which produces the desired size but then (even with `\normalsize` afterwards) seems to break pagination of the references.

**Comment by yihui** [comment]
If you want Markdown to be processed within LaTeX commands or environments, you can use a hack. For LaTeX environments, you can use the `block2` engine of **knitr**, which is currently only available in the devel version of **knitr** on Github.

    ```{block2, type='FOO'}
    Your _markdown_ stuff here.
    ```

This will be translated to

```latex
\BeginKnitrBlock{FOO}
Your \emph{Markdown} stuff here.
\EndKnitrBlock{FOO}
```

Then you have to

```latex
\let\BeginKnitrBlock\begin
\let\EndKnitrBlock\end
```

in the preamble.

For inline commands, you can use this

    \FOO<span>Your _Markdown_ stuff</span>

It will be translated to `\FOO{Your \emph{Markdown} stuff}`.

**Comment by cboettig** [comment]
Closing this out with (4) being recommended as the simplest / most fail-proof strategy.

**Comment by derekpowell** [comment]
Working on this myself, I found it easiest to just edit the .tex file after knitting and manually wrap the stuff I wanted in the materials and methods section in the `/matmethods{}` call. Seems like it wouldn't be too hard to automated that substitution with a script called after knitting?

When I first tried option 4 I had issues with the references overflowing onto the footer.
