### ISSUE TITLE
In ctex template "number_sections: no" doesn't remove section number from header

### ISSUE THREAD

**Issue by adempewolff** [rstudio/rticles#85]
#### Steps to reproduce:
1. Create a new document using the included skeleton file
2. change "number_sections: yes" to "number_sections: no"
3. knit
4. look at the header on pages 2-4 of the output pdf
#### Expected behaviour:

Section numbers will not be displayed in the header.
#### Actual behaviour:

"0" is displayed for the section number on the left-hand side of each page's header
[Example](https://github.com/rstudio/rticles/files/492520/Untitled.pdf)
#### Comments

Unfortunately, I'm not familiar enough with 'tex or pandoc to do much more troubleshooting.  Big thanks to  @yihui et al. for creating a more or less plug and play template (and associated packages) for rendering CJK text!

**Comment by yihui** [comment]
I can reproduce the issue, but I don't know how to solve it. The problem is that Pandoc uses this to suppress section numbering:

```latex
\setcounter{secnumdepth}{0}
```

and unfortunately it leaves an undesired side-effect of the number 0 before section headings in the page headers. CTeX authors are better people to answer this question than me.
